### ISSUE TITLE
messageFromCelcius() - improve messages - base them on more weather info?

### ISSUE THREAD

**Issue by drbonzo** [netguru-training/workshops-rn-2#28]

**Comment by Paulina-Kapka** [comment]
Wyświetlić dodatkowe dane w DayInfoScreen. Jak już bedą dobrze wyświetlane zmienimy funkcję messageFromCelcius():


`payload: {
                id: datetime,
                weather: {
                  temperatureCelcius: temp,
                  icon,
                  possibilityOfPrecipitation: pop,
                  cloudCoverage: clouds,
                  windSpeed: wind_spd
                }
              }
`

**Comment by drbonzo** [comment]
`AddEventScreen` needs this also, inside `<Text style={headerText}>Based on api data</Text>`

**Comment by Paulina-Kapka** [comment]
#33
